.gitignore
README.md

adding few tweaks for dockers beginners

docker beginners guide

---

setup_iotex_testnet.sh

https://github.com/iotexproject/iotex-testnet/issues/14

quick installation script

---

scripts/setup_fullnode.sh

1, add remote run scirpt 
2, add version for tag repo config

add version for tag repo

---

scripts/setup_fullnode.sh

if not permissions exit; remind 'sudo bash'

Determine docker permissions

---

monitor/.env
monitor/Dockerfile
monitor/IoTeX.json
monitor/dashboards.yaml
monitor/datasource.yaml
monitor/docker-compose.yml
monitor/prometheus.yml
monitor/run.sh
scripts/setup_fullnode.sh

Added configuration files for configuring prometheus and grafana. Modified the setup_fullnode.sh to add options for the monitored service

Add monitor for iotex node

---

scripts/setup_fullnode.sh

Fix the issue at https://github.com/iotexproject/iotex-bootstrap/issues/92.

upgrader remove old poll.db.bolt

---

config_mainnet.yaml
config_testnet.yaml

This reverts commit fba2fc67668515326b1eed2d32a80921a3aee30b.

Temporarily Revert "add index path (#79)"

---

scripts/setup_fullnode.sh

fix the color bug miss "${NC}"

fix color bug

---

config_mainnet.yaml
config_testnet.yaml

This reverts commit 410f089abe241be3f5f47017300b60057a7f620b.

Revert "Revert "add index path (#79)" (#100)"

---

scripts/setup_fullnode.sh
scripts/setup_monitor_alert.sh

Check if docker-compose command is installed

Fix sometimes error when running script

---

scripts/setup_monitor_alert.sh

Fix wrong command

---

config_mainnet.yaml
config_testnet.yaml

This reverts commit 198380031fcd424d77ef24beab864602d3650522.

Revert "Revert "Revert "add index path (#79)" (#100)" (#105)"

---

config_testnet.yaml

Reverts iotexproject/iotex-bootstrap#125

Revert "disable splitDB in testnet_config"

---

scripts/setup_fullnode.sh
scripts/update_silence.sh

fix bug auto-update

---

scripts/setup_fullnode.sh

fix some bug for auto-update

---

scripts/setup_fullnode.sh

Add download db file

---

monitor/docker-compose.yml
monitor/docker-compose.yml.gateway

issue: https://github.com/iotexproject/iotex-core/issues/2304
reference: https://docs.docker.com/engine/reference/run/#restart-policies---restart

auto restart after reboot

---

monitor/docker-compose.yml.marketplace
scripts/setup_fullnode_marketplace.sh

Add an install script for marketplace

add install script for marketplace

---

changelog/v1.1-release-note.md

release note 1.1.3

---

README.md

release 1.1.3

---

scripts/setup_fullnode.sh

Add download progress for save snapshot
https://github.com/iotexproject/iotex-core/issues/2539

Add download progress for save snapshot

---

scripts/setup_fullnode.sh

add choose donwload snapshot

---

README.md

[readme] add native babel into readme

---

scripts/setup_fullnode.sh

Changed only description because default of autoupgrade is set to N

---

README.md
README_CN.md
README_CN_testnet.md
README_testnet.md
scripts/setup_fullnode.sh

change the get method of testnet lastversion

change the get method of testnet lastversion

---

README_CN.md
README_CN_testnet.md
README_testnet.md
genesis_testnet.yaml

testnet has been activated at height 22919041

pre-release v1.12.0-rc0 for testnet
